### ISSUE TITLE
[HTML] CTA section issues

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/portum#110]
- optiunile de "stretching" nu sunt implementate in front-end corect
- textul este aliniat la centru, by default

---

![image](https://user-images.githubusercontent.com/7841556/41601550-6d68e50a-73e1-11e8-8208-87dc4c1863f0.png)

**Comment by ngabyn** [comment]
**textul este aliniat la centru, by default** - tested ... all is aligned by left
