### ISSUE TITLE
error in creating pages

### ISSUE THREAD

**Issue by duduxweb** [MachoThemes/portum#186]
Hello,

I need some help, on the Portum theme

when I create a new page, I custom it with sections specific to the page, but when I open the page (site.com/new-page) it opens with the sections of the main page.

is it some mistake?
this happens with any page I create.

hug

**Comment by cristianraiber** [comment]
@duduxweb - Go here: http://colorlib.com/downloads/portum.zip download & install this version of Portum.

Your problem will be fixed.

**Comment by duduxweb** [comment]
Hello, after installing this version there were several errors.

Would you help me?

```
Notice: Undefined variable: header_class in /home/site/public_html/wp-content/themes/portum/header.php on line 20

Notice: Undefined index: slider_pager in /home/site/public_html/wp-content/themes/portum/template-parts/frontpage/slider-section.php on line 51

Notice: Undefined index: services_section_visibility in /home/site/public_html/wp-content/themes/portum/template-parts/frontpage/services-section.php on line 27

Notice: Undefined index: cta_section_visibility in /home/site/public_html/wp-content/themes/portum/template-parts/frontpage/cta-section.php on line 16

Notice: Undefined index: pricing_section_visibility in /home/site/public_html/wp-content/themes/portum/template-parts/frontpage/pricing-section.php on line 26

Notice: Undefined index: expertise_section_visibility in /home/site/public_html/wp-content/themes/portum/template-parts/frontpage/expertise-section.php on line 25

Notice: Undefined index: clientlist_section_visibility in /home/site/public_html/wp-content/themes/portum/template-parts/frontpage/clientlist-section.php on line 26

Notice: Undefined index: shortcodes_section_visibility in /home/site/public_html/wp-content/themes/portum/template-parts/frontpage/shortcodes-section.php on line 26


```

**Comment by cristianraiber** [comment]
@duduxweb - go into Customizer, modify any value, delete the modification, hit save :)

**Comment by duduxweb** [comment]
> @duduxweb - go into Customizer, modify any value, delete the modification, hit save :)

Perfect.

apenas o não teve a correção.

Notice: Undefined variable: header_class in /home/serverhot/public_html/wp-content/themes/portum/header.php on line 20
