### ISSUE TITLE
Using more than 6 testimonials in a single testimonials section breaks layout

### ISSUE THREAD

**Issue by underd0se** [MachoThemes/portum#187]
If you have more than 6 testimonials and select` Show:All`, testimonials layout gets broken. 

Example: I have 22 testimonials and only way to make them show properly is group them in 4's and place those groups in seperate testimonails section (total of 5 sections as 6+4+4+4+4). However, if I try to edit/add/delete any of the testimonials, all sections' selections reset to `Show:All` and layout gets broken again. 

Steps to reproduce layout bug:  

Add a Testimonials section into a page
Add more than 6 entries (22 in my case) 
Select `Testimonials to Show: All` 
Layout gets broken (7th entry is misaligned to the center of the page)

Steps to reproduce reset selection bug: 

Add 2 Testimonials section into a page
Add more than 6 entries (i.e: 15) 
Select `Testimonials to Show` for the first  section as `Entry1, Entry2,....Entry6`
Select `Testimonials to Show` for the second section as `Entry7, Entry8,....Entry10`
Save & Publish
Edit, add or remove any testimonial entry or section
All testimonial selections for sections reset to `Show:All`

**Comment by cristianraiber** [comment]
@underd0se - completely aware of it. Next Portum version will have a completely different layout and styling. Will post here once it's released :) 

Cristian.
