### ISSUE TITLE
Duplicate sections when using epsilon builder sections with child elements

### ISSUE THREAD

**Issue by assaflei** [MachoThemes/portum#189]
Hi,
I noticed that when using more than one section containing child entries (services, portfolio, advanced slider) all the sections contain the same data.
Issue not happening for sections without sub entities (alt. image text which I used a lot)

Steps to reproduce:
1. Add advanced slider section 
2. Set one slide
3. Add another advanced slider section
4. Set one slide
5. Text of first slide changes to the same text as the new child

**Comment by cristianraiber** [comment]
@assaflei - please notice & use the filtering field :) That's why it's there! There's an entire field that allows you to "filter" the content you want shown per section.

**Comment by assaflei** [comment]
Will try it, thanks
