### ISSUE TITLE
How to create a regular page?

### ISSUE THREAD

**Issue by lumberg72** [MachoThemes/portum#215]
I'm new to WP, so I'm not 100% sure if this is a Portum theme question or a generic WP question.
My homepage looks great, but now I want to add some pages and link to them (a page for each product, etc). But the pages always look like blog posts. They have comments information, post date, author, etc at the bottom. I don't want anything to do with blogging on my site.
I just want a regular static page that fits with the overall Portum theme. Seems like it's not possible (at least not easily).
Am I missing something?
Thanks

P.S. Beautiful theme... nicely done

**Comment by cristianraiber** [comment]
@lumberg72 - Can you please make sure you've set a static page as your homepage? :) 

Also, which version of Portum are you running ?

**Comment by lumberg72** [comment]
I thought I was using the latest. But after your comment, I checked and upgraded from 1.0.2 to 1.0.4. Now I see there is an "add page" option in the page builder (previously, I was having to do it from WP admin console).
Anyway... this seems to be doing exactly what I needed now.
Thanks for your response.

**Comment by cristianraiber** [comment]
Glad it's fixed :)
