### ISSUE TITLE
 Uncaught Error: Class 'Epsilon_Framework' not found

### ISSUE THREAD

**Issue by lglucas** [MachoThemes/portum#226]
Fatal error: Uncaught Error: Class 'Epsilon_Framework' not found in /home/lucas486/public_html/gotta/wp-content/themes/portum-master/inc/class-portum.php:170 Stack trace: #0 /home/lucas486/public_html/gotta/wp-content/themes/portum-master/inc/class-portum.php(78): Portum->init_epsilon() #1 /home/lucas486/public_html/gotta/wp-content/themes/portum-master/inc/class-portum.php(93): Portum->__construct(Object(WP_Theme)) #2 /home/lucas486/public_html/gotta/wp-content/themes/portum-master/functions.php(18): Portum::get_instance() #3 /home/lucas486/public_html/gotta/wp-settings.php(497): include('/home/lucas486/...') #4 /home/lucas486/public_html/gotta/wp-config.php(94): require_once('/home/lucas486/...') #5 /home/lucas486/public_html/gotta/wp-load.php(37): require_once('/home/lucas486/...') #6 /home/lucas486/public_html/gotta/wp-login.php(12): require('/home/lucas486/...') #7 {main} thrown in /home/lucas486/public_html/gotta/wp-content/themes/portum-master/inc/class-portum.php on line 170

**Comment by cristianraiber** [comment]
@lglucas - that's not the way to download Portum from Github. It uses GitHub submodules. Use ```git clone --recursive ```
